### ISSUE TITLE
Error deploying to AWS on eu-west-1

### ISSUE THREAD

**Issue by adrianmelero** [radiantearth/lambda-tiler#8]
When executing sls deploy ( modifying region on serverles.yml to eu-west-1)

The error code is: 

User: arn:aws:iam::xxxxxxxxxxx:user/xxxxxxxxxxxxxx is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:eu-west-1:524387336408:layer:gdal30-py37-cogeo:8 (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: b36426f7-2d28-4241-9194-9711705e789a)

It seems that is a zone problem, I need to deploy it on eu-west-1.

Thanks.

**Comment by HamedAlemo** [comment]
Hi @adrianmelero, This repository is not actively maintained, and it's a fork of the original project by @vincentsarago
Please check the source repository (https://github.com/vincentsarago/lambda-tiler) for any updates that addresses this issue, or reach out to Vincent. 

Hamed
